CREATE TABLE "Actions" (
    "id" SERIAL PRIMARY KEY,
    "HabitID" INTEGER NOT NULL REFERENCES "Habits"(id) ON DELETE CASCADE,
    "UserID" INTEGER NOT NULL,
    "LoggedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 